/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import { useState } from 'react'

interface Props {
  icon: string
  title: string
  subtitle?: string
}

const Card = ({ icon, title, subtitle }: Props) => (
  <div className="w-full bg-white rounded-lg py-10 lg:pb-14 xl:pb-20 2xl:pb-20 px-5">
    <img src={icon} alt="one Month" className="mx-auto pt-4 lg:w-[120px] xl:w-[150px] 2xl:w-[200px] lg:h-[120px] xl:h-[150px] 2xl:h-[200px]" />

    <div className="text-center pt-6 2xl:pt-8">
      <h1 className="text-[#008080] text-sm xl:text-base 2xl:text-lg font-bold">{title}</h1>
      <p className="text-[#333333] text-sm xl:text-base 2xl:text-base pt-4 px-2 2xl:pt-5">{subtitle}</p>
    </div>
  </div>
)

export default function Login() {
  const [visible, setVisible] = useState<boolean>(false)

  return (
    <>
      <Head>
        <title>B2b Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full px-8">
        <div className="flex justify-between">
          <div>
            <h1 className="text-[#333333] text-xl 2xl:text-xl font-[1000] tracking-wide">
              Loans
            </h1>
            <p className="text-sm 2xl:text-base pt-2 text-[#333333 tracking-wide">
              <span className="text-[#008080] font-bold">Monday</span> , 21st
              February, 2021
            </p>
          </div>
        </div>

        {/* <div className="sm:block sm:space-y-4 space-y-0 lg:flex xl:flex 2xl:flex lg:space-x-6 xl:space-x-6 2xl:space-x-6 pt-6 md:grid md:grid-cols-2 md:space-x-0 md:gap-x-6 md:gap-y-8 ">
          <Card
            icon="./oneMonth.svg"
            title="One Month Loan"
            subtitle="Access funds for personal upkeep for 30 days only"
          />
          <Card
            icon="./capital.svg"
            title="Working Capital Overdraft"
            subtitle="Access continuous funds to grow your business stocks and inventory"
          />{' '}
          <Card
            icon="./oneMonth.svg"
            title="One Month Loan"
            subtitle="Access funds for personal upkeep for 30 days only"
          />{' '}
          <Card
            icon="./oneMonth.svg"
            title="One Month Loan"
            subtitle="Access funds for personal upkeep for 30 days only"
          />
        </div>
        <div className="sm:block sm:space-y-4 space-y-0  lg:flex xl:flex 2xl:flex lg:space-x-6 xl:space-x-6 2xl:space-x-6 pt-6 md:grid md:grid-cols-2 md:space-x-0 md:gap-x-6 md:gap-y-8 xl:space-y-0">
          <Card
            icon="./oneMonth.svg"
            title="One Month Loan"
            subtitle="Access funds for personal upkeep for 30 days only"
          />
          <Card
            icon="./oneMonth.svg"
            title="One Month Loan"
            subtitle="Access funds for personal upkeep for 30 days only"
          />{' '}
          <Card
            icon="./oneMonth.svg"
            title="One Month Loan"
            subtitle="Access funds for personal upkeep for 30 days only"
          />{' '}
          <Card
            icon="./oneMonth.svg"
            title="One Month Loan"
            subtitle="Access funds for personal upkeep for 30 days only"
          />
        </div> */}


         <div className="grid md:grid-cols-2 lg:grid-cols-3 pt-8 gap-4 xl:grid-cols-4 2xl:grid-cols-4">
          <Card
            icon="./oneMonth.svg"
            title="One Month Loan"
            subtitle="Access funds for personal upkeep for 30 days only"
          />
          <Card
            icon="./capital.svg"
            title="Working Capital Overdraft"
            subtitle="Access continuous funds to grow your business stocks and inventory"
          />{' '}
          <Card
            icon="./operation-overdraft.svg"
            title="Operation Overdraft"
            subtitle="Financing for your business operations"
          />{' '}
          <Card
            icon="./t&t.svg"
            title="T and T Spread Loan"
            subtitle=" Purchase phones, generators and vehicles on a reasonable payment plan from T and T Deals Market"
          />
          <Card
            icon="./infrastructure.svg"
            title="Infrastrusture Loan"
            subtitle="Facility for your business to purchase vehicles, assets, and building upgrades."
          />
          <Card
            icon="./personal.svg"
            title="Personal Loan"
            subtitle="Instant funds for your personal expenses."
          />{' '}
          <Card
            icon="./pawn.svg"
            title="Pawn Loan"
            subtitle="Get cash value on temporary sale of your items within 72hours."
          />{' '}
          <Card
            icon="./dollar.svg"
            title="FX line"
            subtitle="Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
          />
        </div>
      </div>
    </>
  )
}
